version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi-container
    ports:
      - "8080:8080"  # NiFi Web UI port
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - nifi-data:/opt/nifi/nifi-current/logs
    networks:
      - airflow-network

volumes:
  nifi-data:
  
networks:
  airflow-network:
